name: software_engineering_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

  curved_navigation_bar: ^1.0.3 #latest version

  english_words: ^4.0.0
  provider: ^6.0.0
<<<<<<< Updated upstream
=======
  firebase_core: ^2.25.2
  http: ^1.2.0
>>>>>>> Stashed changes
  firebase_core: ^2.25.2
<<<<<<< HEAD
  cloud_firestore: ^4.15.4

=======
>>>>>>> 1aa03e231c0c0913e22b30773588e6225e9275ac

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
<<<<<<< Updated upstream
  uses-material-design: true
=======
  uses-material-design: true
  assets:
    - images/lambda.jpg
    - assets/images/background.png
    - assets/data/stocks.json
    
>>>>>>> Stashed changes

  assets:
    - lib/images/background.png